### ISSUE TITLE
Middle Man Service Overrides

### ISSUE THREAD

**Issue by AktionP** [YCPRadioTelescope/YCP-RT-ControlRoom#149]
In order to ensure that the mobile app and front end teams can override the sensors from their devices when things get bad while they are not on site, we need to make sure the middle man service can send and receive these commands, and use it to control the control room application

**Comment by kkennelly** [comment]
Just to give you guidelines to start... you will need to find where we do the tcp connection, confer with Alyssa about what the structure of the message will be for setting overrides, and then implement analysis of the string message to turn on/off certain overrides. Since you already know how to set these overrides, the hardest part is going to get access to the classes that have those methods.
