### ISSUE TITLE
Fix memory leaks in RemoteListener

### ISSUE THREAD

**Issue by pdnelson** [YCPRadioTelescope/YCP-RT-ControlRoom#300]
As it stands, the `RemoteListener` uses plenty of objects that implement `IDisposable` that are not being disposed of. One of these is `NetworkStream`, though there could be more; it is up to the assignee to investigate this.

It is important to note that just creating a new instance of an object over top of the old instance does NOT dispose of the used memory, it simply gives it a new memory address. That is the main problem with the current implementation.

This also includes bringing down the `RemoteListener` when a Telescope is shut down, thus calling all objects' disposals. Such a function should:
- Close the `NetworkStream` (may throw exception; surround in try/catch)
- Stop the `TcpListener`
- Dispose everything that's disposable (should be the `NetworkStream` and `TcpClient`, but check for other things)

**Comment by tfranks31** [comment]
These requirements have changed since the `RemoteListener` refactor. I looked through all of `RemoteListener` for any objects that use `IDisposable` aside from the ones mentioned above and found no other objects needed to be disposed of. There were also no cases of creating new objects over any disposable objects.

The only thing that needs to be checked is that `IDisposable` objects (`NetworkStream` and `TcpClient`) are guaranteed to be disposed of. The only situation I see where they are not disposed of is if an exception is thrown at some point in a client thread. I recommend adding `using` statements for the `IDisposable` objects to guarantee that the objects will be disposed of if an exception disrupts the thread.

**Comment by jsnyder17** [comment]
Fixed with "using" statement when initializing TcpClient and NetworkStream
