### ISSUE TITLE
Move Thermal Calibrate into RTController

### ISSUE THREAD

**Issue by pdnelson** [YCPRadioTelescope/YCP-RT-ControlRoom#364]
At the moment, Thermal calibrate calls a series of Move_to_orientation movements and things that depend on the parent RadioTelescope. For this reason, it should be moved into the `RadioTelescopeController` so that we don't have to do any funky stuff in `ProductionPLCDriver`. This way, the PLC driver is cleaned up, and our abstraction is being used correctly.

What this move accomplishes:
- Removal of `Parent` `RadioTelescope` in `ProductionPLCDriver` 
  - Remove `setParent` from `AbstractPLCDriver`
  - Remove `getParent` from `AbstractPLCDriver`
  - Remove anything that passes the parent to the PLC driver
- Removal of `Thermal_Calibrate` from all PLC drivers
- `ThermalCalibrateRadioTelescope` will contain all thermal calibration functionality, making calls to `MoveRadioTelescopeToOrientation` to accomplish its movements

**Comment by DanPalm5** [comment]
Upon removing these things and running the CR, we get an exception here in `PushNotifications.cs`:
![image](https://user-images.githubusercontent.com/57024625/114967084-cd569b00-9e41-11eb-978e-6b66d9604611.png)

It is caused by the firebase ID being null when retrieved from the database:
![image](https://user-images.githubusercontent.com/57024625/114967299-33dbb900-9e42-11eb-9caa-5443675d4450.png)

This comes from the push notification of "Gate Open".  I will investigate further.
