### ISSUE TITLE
The RF graph should not say "Frequency" on the x-axis

### ISSUE THREAD

**Issue by pdnelson** [YCPRadioTelescope/YCP-RT-ControlRoom#418]
In the UI editor window, it correctly displays "Time"
When a scan is manually initiated, it correctly displays "Time" and keeps track of the time accurately

However, when an appointment is run, this is what it looks like:
![image](https://user-images.githubusercontent.com/48131480/117631044-d50c1580-b149-11eb-9279-093fa0eaf2cb.png)

The assignee will need to investigate why this is occurring, and what is different between when appointments scan vs RTControl scans.

**Comment by tfranks31** [comment]
It turns out that "Frequency" is displayed because the SpectraCyber is performing a "Spectral" scan, and "Time" is displayed for "Continuum" scans. This is intentional and is working as expected, so there is no bug to fix. I updated the General Documentation and User Interface Documentation in our Google Drive to note the differences for SpectraCyber scan types.
