### ISSUE TITLE
Parse Acceleration Data

### ISSUE THREAD

**Issue by davidmchugh2000** [YCPRadioTelescope/YCP-RT-ControlRoom#420]
Acceleration Data is stored in the `acceration_blob `table and needs to be extracted for admin use. `acc_blob ` stores a string for 4,000 acceleration values. Each value is separated by ~ and each acceleration object is separated by -. String us built in the `AccelerationBlob `class

See Todd on how he wants this information received 

Each Accelerations Stores 
- Acceleration
- X
- Y
- Z
- location_ID

**Comment by andersonjackc** [comment]
I currently am working on parsing the blobs on this branch: https://github.com/YCPRadioTelescope/YCP-RT-ControlRoom/tree/acceleration-blob

I have added a parsing function, however; in creating that I encountered a few unpredicted outcomes in the actual stored data, detailed below.  I will be meeting with David to discuss the next steps for this, in order to ensure that the correct acceleration data is being stored.

As mentioned in the original issue, the acceleration data is supposed to be blobbed together as follows
acc~x~y~z~loc_ID-

When examining the database I came across the following behavior:
![image](https://user-images.githubusercontent.com/60368246/134350039-1d1ef46c-4bca-40e3-bc8b-6db838a6c5d0.png)
which makes me think that some acceleration data points are being stored without specific fields, such as x,y,z or location ID.

I also encountered:
![image](https://user-images.githubusercontent.com/60368246/134350184-292d57b8-a7c4-4051-8591-ef3f082b85d5.png)
I am not entirely sure what would cause that.

**Comment by andersonjackc** [comment]
As an update for this issue, I have changed the delimiter from a - to a $ in this commit: https://github.com/YCPRadioTelescope/YCP-RT-ControlRoom/commit/2ec88c911416ad81e5cd2033babeb4f5e940dabf

I have also discovered that the huge chunk of hyphens and + symbols is SQL attempting to beautify the output of the table, as seen in this other tables output:
![image](https://user-images.githubusercontent.com/60368246/134530296-0f32c4e3-aef2-4252-b0bf-3fb6ac2a5fb0.png)

The blobs of acceleration data will be parsable after merging this change.

**Comment by andersonjackc** [comment]
This issue has been completed, as it was opened to create a parsing function for the existing blob, which led to the entire redesign and re-implementation of the blob.  A parsing function does now exist for the blob.

A new issue has been created for graphing this data: https://github.com/YCPRadioTelescope/YCP-RT-ControlRoom/issues/467
