### ISSUE TITLE
Integrate new sensors into the sensor network and implement sensor customizability

### ISSUE THREAD

**Issue by DanPalm5** [YCPRadioTelescope/YCP-RT-ControlRoom#427]
We will need to integrate and successfully collect data (and likely display it) from the new sensors we have acquired. This will be able to be completed after the encoders are put on.

**Comment by tfranks31** [comment]
Fasten your seatbelt... two new devices need to be integrated into the Sensor Network and a new feature that needs to be added. The new devices are a DHT22 ambient temperature sensor and an internal fan, and the new feature is sensor customizability from the Control Room.

The DHT22 will need to have its data parsed from the incoming packet and displayed on the `Sensor Data` tab of the Diagnostics form. Also, find out if we need to store this data in the database for future analysis (we probably will). Make sure to update the Simulation Sensor Network, associated unit tests, and the Sensor Network Testing Suite.

Integrating the internal fan will take a bit more work. The Control Room needs to tell the fan when to turn on and turn off. After the Control Room connects to and initializes the ESS, it only listens for incoming sensor data packets. We need it to send requests to turn on or off the fan when a certain temperature/humidity reading is reached, so we need to refactor our communication protocol with the ESS to be 2-way. Check that this new protocol still supports data transfer rates that we need elsewhere in the Control Room Application. The incoming sensor data packet will have a new bit, saying whether the fan is currently on or off, which needs to be parsed and displayed on the diagnostics form's `Sensor Data` tab. Allow the user to change the temperature and humidity thresholds from a form and store them in the database so that information persists over.

The Simulation Sensor Network will need to accommodate this 2-way change, and unit tests will need to be updated. The Sensor Network Testing Suite needs to be updated and allow the user to send requests to start and stop the fan. Find out if we need to store when the fan is used in the database. Find out if the user should be able to toggle the fan manually from a form.

Since we are implementing a two-way protocol here, we should also allow the Control Room to customize and store sensor settings as the ESS is running. This will likely involve changing the `Sensor Overrides/Init` tab or creating a new tab on the Diagnostics form. Find out what the clients want to do first. Then find out all of the different customization options that our sensors offer and allow the user to change them from the form. Make sure to validate all user inputs before letting them submit.

The Simulation Sensor Network shouldn't need too many changes because the simulated data produced will still be the same. Just make sure that nothing breaks when changing sensor settings on the simulation. Add and modify units tests for these changes as well. Modify the Sensor Network Testing Suite to send sensor configurations as well. Lastly, we need to store the configurations in the database so that they persist over after the Control Room Application is closed.

---
That was a whole lot of info! Here is a task list to help keep track of everything that needs to be done.

### DHT22 - Find out if we need to store data
- [ ] Parse and display data
- [ ] Update the Sensor Network Testing Suite to display incoming temperature data and create simulated temperature data CSVs and test packets
- [ ] Update simulation sensor network to send new fake data
- [ ] Update and add unit tests
- [ ] (if needed) Add new database table and store temperature data

### Internal Fan - Find out if we need to store data and if the fan can be manually toggled
- [ ] Parse and display data
- [ ] Implement 2-way communication protocol
- [ ] Add temperature and humidity thresholds to the database
- [ ] Make temperature and humidity thresholds changeable from a form
- [ ] Send fan on and off requests when certain temperature and humidity thresholds are reached
- [ ] Update simulation sensor network to receive communications and turn the fan on or off
- [ ] Update the Sensor Network Testing Suite to display if the fan is on or off, use the 2-way protocol, send signals to toggle the fan, and generate new test packets
- [ ] Update and add unit tests
- [ ] (if needed) Add a new database table to store when the fan is on
- [ ] (if needed) Add a toggle to a form to manually turn the fan on or off

### Sensor Custimizability
- [ ] Allow user to change sensor settings and submit them from a form
- [ ] Store sensor configurations in database
- [ ] Send sensor configuration to ESS
- [ ] Check that the simulation sensor network still works
- [ ] Modify Sensor Network Testing Suite to send configurations
- [ ] Update and add unit tests
